version: 0.2

env:
  variables:
    StackName: "generativeAI"
    S3BucketName: "metalmental-myblog-generativeai-codepipeline-s3"

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - ls -l
  build:
    commands:
      - python -m venv myenv
      - source myenv/bin/activate
      - mkdir -p lambda_layer/python
      - mv requirements.txt lambda_layer/
      - pip install -r lambda_layer/requirements.txt -t lambda_layer/python
  post_build:
    commands:
      - sam build --template-file template.yaml
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file package.yml --s3-bucket "${S3BucketName}"
      - sam deploy --template-file package.yml --stack-name "${StackName}" --capabilities CAPABILITY_NAMED_IAM
